
using Sitecore.Diagnostics.PerformanceCounters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Sitecore.Support.Diagnostics.PerformanceCounters
{
    public static class PresentationCount
    {
        /// <summary>
        /// Gets the counter that counts the total number of times the active site has been changed by the API.
        /// </summary>
        /// <value>
        /// The counter instance.
        /// </value>
        public static AmountPerSecondCounter ContextSiteChanged
        {
            get;
            private set;
        }

        /// <summary>
        /// Gets the counter that counts the total number of Sitecore controls rendered.
        /// </summary>
        /// <value>
        /// The counter instance.
        /// </value>
        public static AmountPerSecondCounter RenderingControlsRendered
        {
            get;
            private set;
        }

        /// <summary>
        /// Gets the counter that counts the total number of Sitecore controls rendered from a cache.
        /// </summary>
        /// <value>
        /// The counter instance.
        /// </value>
        public static AmountPerSecondCounter RenderingControlsRenderedFromCache
        {
            get;
            private set;
        }

        /// <summary>
        /// Gets the counter that counts the total number of web pages generated by Sitecore.
        /// </summary>
        /// <value>
        /// The counter instance.
        /// </value>
        public static AmountPerSecondCounter RenderingPagesGenerated
        {
            get;
            private set;
        }

        /// <summary>
        /// Gets the counter that counts the total number of Renderings rendered.
        /// </summary>
        /// <value>
        /// The counter instance.
        /// </value>
        public static AmountPerSecondCounter RenderingRenderingsRendered
        {
            get;
            private set;
        }

        /// <summary>
        /// Gets the counter that counts the total number of Sublayouts rendered.
        /// </summary>
        /// <value>
        /// The counter instance.
        /// </value>
        public static AmountPerSecondCounter RenderingSublayoutsRendered
        {
            get;
            private set;
        }

        /// <summary>
        /// Gets the counter that counts the total number of XmlControls compiled.
        /// </summary>
        /// <value>
        /// The counter instance.
        /// </value>
        public static AmountPerSecondCounter RenderingXmlControlsCompiled
        {
            get;
            private set;
        }

        /// <summary>
        /// Gets the counter that counts the total number of XslTransforms rendered.
        /// </summary>
        /// <value>
        /// The counter instance.
        /// </value>
        public static AmountPerSecondCounter RenderingXslTransformsRendered
        {
            get;
            private set;
        }

        /// <summary>
        /// Gets the counter that counts the total number of XamlControls compiled.
        /// </summary>
        /// <value>
        /// The counter instance.
        /// </value>
        public static AmountPerSecondCounter RenderingXamlControlsCompiled
        {
            get;
            private set;
        }

        /// <summary>
        /// Initializes static members of the <see cref="T:Sitecore.Diagnostics.AmountPerSecondCounters.PresentationCount" /> class.
        /// </summary>
        static PresentationCount()
        {
            try
            {
                PresentationCount.ContextSiteChanged = new AmountPerSecondCounter("Context | Site Changed / sec", "Sitecore.Presentation");
                PresentationCount.RenderingControlsRendered = new AmountPerSecondCounter("Rendering | Controls Rendered / sec", "Sitecore.Presentation");
                PresentationCount.RenderingControlsRenderedFromCache = new AmountPerSecondCounter("Rendering | Controls Rendered From Cache / sec", "Sitecore.Presentation");
                PresentationCount.RenderingPagesGenerated = new AmountPerSecondCounter("Rendering | Pages Generated / sec", "Sitecore.Presentation");
                PresentationCount.RenderingRenderingsRendered = new AmountPerSecondCounter("Rendering | Renderings Rendered / sec", "Sitecore.Presentation");
                PresentationCount.RenderingSublayoutsRendered = new AmountPerSecondCounter("Rendering | Sublayouts Rendered / sec", "Sitecore.Presentation");
                PresentationCount.RenderingXmlControlsCompiled = new AmountPerSecondCounter("Rendering | XmlControls Compiled / sec", "Sitecore.Presentation");
                PresentationCount.RenderingXslTransformsRendered = new AmountPerSecondCounter("Rendering | Xsl Transforms Rendered / sec", "Sitecore.Presentation");
                PresentationCount.RenderingXamlControlsCompiled = new AmountPerSecondCounter("Rendering | Xaml Controls Compiled / sec", "Sitecore.Presentation");
            }
            catch (System.Exception)
            {
            }
        }
    }
}
